name: Tellyfish
favicon: null
layout_spectrum: 0.47436364204622805
typography_spectrum: 0.9624880328774452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5043969133403152
  lightness: 0.06963617959991097
  saturation: 0.4138910372275859
  rhythmicContrast: 0.8375901924446225
purpose: []
